services:
  - type: web
    name: streamchatter
    env: python
    plan: free
    buildCommand: pip install -r llama_chat/requirements.txt
    startCommand: uvicorn src.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OUTPUTS_DIR
        value: /opt/render/project/src/llama_chat/src/temp/outputs
      # Add other environment variables as needed